-- Insert 51 Games into Spica Database
USE spica_games;

INSERT INTO games (name, genre_id, platforms) VALUES
('Minecraft', 1, '["PC", "PlayStation", "Xbox", "Switch", "Mobile"]'),
('Grand Theft Auto V', 2, '["PC", "PlayStation", "Xbox"]'),
('Red Dead Redemption 2', 3, '["PC", "PlayStation", "Xbox"]'),
('The Witcher 3: Wild Hunt', 4, '["PC", "PlayStation", "Xbox", "Switch"]'),
('Elden Ring', 5, '["PC", "PlayStation", "Xbox"]'),
('Cyberpunk 2077', 4, '["PC", "PlayStation", "Xbox"]'),
('Skyrim', 4, '["PC", "PlayStation", "Xbox", "Switch"]'),
('God of War Ragnarök', 7, '["PlayStation"]'),
('Ghost of Tsushima', 2, '["PlayStation", "PC"]'),
('Spider-Man 2', 2, '["PlayStation"]'),
('The Last of Us', 8, '["PlayStation", "PC"]'),
('Uncharted 4', 7, '["PlayStation", "PC"]'),
('Horizon Forbidden West', 4, '["PlayStation", "PC"]'),
('Bloodborne', 9, '["PlayStation"]'),
('Sekiro: Shadows Die Twice', 10, '["PC", "PlayStation", "Xbox"]'),
('Dark Souls III', 9, '["PC", "PlayStation", "Xbox"]'),
('Fortnite', 11, '["PC", "PlayStation", "Xbox", "Switch", "Mobile"]'),
('PUBG: Battlegrounds', 11, '["PC", "PlayStation", "Xbox", "Mobile"]'),
('Apex Legends', 12, '["PC", "PlayStation", "Xbox", "Switch"]'),
('Call of Duty: Warzone', 13, '["PC", "PlayStation", "Xbox"]'),
('Counter-Strike 2', 14, '["PC"]'),
('Valorant', 15, '["PC"]'),
('Rainbow Six Siege', 15, '["PC", "PlayStation", "Xbox"]'),
('Overwatch 2', 16, '["PC", "PlayStation", "Xbox", "Switch"]'),
('League of Legends', 17, '["PC"]'),
('Dota 2', 17, '["PC"]'),
('Teamfight Tactics', 18, '["PC", "Mobile"]'),
('Rocket League', 19, '["PC", "PlayStation", "Xbox", "Switch"]'),
('FIFA 23', 20, '["PC", "PlayStation", "Xbox", "Switch"]'),
('EA Sports FC 25', 20, '["PC", "PlayStation", "Xbox"]'),
('NBA 2K24', 21, '["PC", "PlayStation", "Xbox"]'),
('Forza Horizon 5', 22, '["PC", "Xbox"]'),
('Gran Turismo 7', 23, '["PlayStation"]'),
('Need for Speed Heat', 24, '["PC", "PlayStation", "Xbox"]'),
('Mario Kart 8 Deluxe', 24, '["Switch"]'),
('Super Mario Odyssey', 25, '["Switch"]'),
('The Legend of Zelda: Breath of the Wild', 2, '["Switch"]'),
('The Legend of Zelda: Tears of the Kingdom', 2, '["Switch"]'),
('Animal Crossing: New Horizons', 30, '["Switch"]'),
('Hollow Knight', 26, '["PC", "PlayStation", "Xbox", "Switch"]'),
('Cuphead', 27, '["PC", "PlayStation", "Xbox", "Switch"]'),
('Celeste', 25, '["PC", "PlayStation", "Xbox", "Switch"]'),
('Terraria', 1, '["PC", "PlayStation", "Xbox", "Switch", "Mobile"]'),
('Stardew Valley', 28, '["PC", "PlayStation", "Xbox", "Switch", "Mobile"]'),
('Subnautica', 29, '["PC", "PlayStation", "Xbox", "Switch"]'),
('The Sims 4', 30, '["PC", "PlayStation", "Xbox"]'),
('Microsoft Flight Simulator', 31, '["PC", "Xbox"]'),
('Cities: Skylines', 32, '["PC", "PlayStation", "Xbox", "Switch"]'),
('Age of Empires II', 33, '["PC", "Xbox"]');